name: 自动获取ss节点

on:
  workflow_dispatch:  # 使工作流支持手动触发
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当创建 PR 到 main 分支时触发

jobs:
  build:
    runs-on: macos-latest  # 在 macOS 上编译

    steps:
      - name: 获取仓库代码
        uses: actions/checkout@v3  # 获取代码

      - name: 执行文件点击打开获取ss节点信息
        run: ./ss
